export type WordDifficulty = 'lako' | 'srednje' | 'tesko';

export interface WordEntry {
  word: string;
  difficulty: WordDifficulty;
}

export const DRAWING_WORDS: WordEntry[] = [
  // LAKO
  { word: 'mačka', difficulty: 'lako' },
  { word: 'pas', difficulty: 'lako' },
  { word: 'kuća', difficulty: 'lako' },
  { word: 'drvo', difficulty: 'lako' },
  { word: 'sunce', difficulty: 'lako' },
  { word: 'auto', difficulty: 'lako' },
  { word: 'avion', difficulty: 'lako' },
  { word: 'krava', difficulty: 'lako' },
  { word: 'riba', difficulty: 'lako' },
  { word: 'jabuka', difficulty: 'lako' },
  { word: 'banana', difficulty: 'lako' },
  { word: 'voz', difficulty: 'lako' },
  { word: 'brod', difficulty: 'lako' },
  { word: 'srce', difficulty: 'lako' },
  { word: 'zvijezda', difficulty: 'lako' },
  { word: 'knjiga', difficulty: 'lako' },
  { word: 'lampa', difficulty: 'lako' },
  { word: 'sat', difficulty: 'lako' },
  { word: 'lopta', difficulty: 'lako' },
  { word: 'torta', difficulty: 'lako' },
  { word: 'kišobran', difficulty: 'lako' },
  { word: 'šešir', difficulty: 'lako' },
  { word: 'cipela', difficulty: 'lako' },
  { word: 'pizza', difficulty: 'lako' },
  { word: 'telefon', difficulty: 'lako' },
  { word: 'stolica', difficulty: 'lako' },
  { word: 'sto', difficulty: 'lako' },
  { word: 'vrata', difficulty: 'lako' },
  { word: 'prozor', difficulty: 'lako' },
  { word: 'šargarepa', difficulty: 'lako' },
  { word: 'lubenica', difficulty: 'lako' },
  { word: 'slon', difficulty: 'lako' },
  { word: 'lav', difficulty: 'lako' },
  { word: 'majmun', difficulty: 'lako' },
  { word: 'žirafa', difficulty: 'lako' },
  { word: 'pingvin', difficulty: 'lako' },
  { word: 'snjegović', difficulty: 'lako' },
  { word: 'šargarepa', difficulty: 'lako' },
  { word: 'nož', difficulty: 'lako' },
  { word: 'čekić', difficulty: 'lako' },
  { word: 'gitara', difficulty: 'lako' },
  { word: 'bubanj', difficulty: 'lako' },
  { word: 'violina', difficulty: 'lako' },
  { word: 'flauta', difficulty: 'lako' },
  { word: 'miš', difficulty: 'lako' },
  { word: 'zec', difficulty: 'lako' },
  { word: 'konjić', difficulty: 'lako' },
  { word: 'patka', difficulty: 'lako' },
  { word: 'ptica', difficulty: 'lako' },
  { word: 'ljestve', difficulty: 'lako' },
  { word: 'konopac', difficulty: 'lako' },
  { word: 'balon', difficulty: 'lako' },
  { word: 'raketa', difficulty: 'lako' },
  { word: 'pauk', difficulty: 'lako' },
  { word: 'kornjača', difficulty: 'lako' },

  // SREDNJE
  { word: 'vatromet', difficulty: 'srednje' },
  { word: 'duga', difficulty: 'srednje' },
  { word: 'oluja', difficulty: 'srednje' },
  { word: 'vulkan', difficulty: 'srednje' },
  { word: 'ostrvo', difficulty: 'srednje' },
  { word: 'džungla', difficulty: 'srednje' },
  { word: 'piramida', difficulty: 'srednje' },
  { word: 'zamak', difficulty: 'srednje' },
  { word: 'robot', difficulty: 'srednje' },
  { word: 'astronaut', difficulty: 'srednje' },
  { word: 'superheroj', difficulty: 'srednje' },
  { word: 'vještica', difficulty: 'srednje' },
  { word: 'duh', difficulty: 'srednje' },
  { word: 'zmaj', difficulty: 'srednje' },
  { word: 'jednosrog', difficulty: 'srednje' },
  { word: 'tornado', difficulty: 'srednje' },
  { word: 'tsunami', difficulty: 'srednje' },
  { word: 'laboratorija', difficulty: 'srednje' },
  { word: 'teretana', difficulty: 'srednje' },
  { word: 'pozorište', difficulty: 'srednje' },
  { word: 'svemirski brod', difficulty: 'srednje' },
  { word: 'ronilac', difficulty: 'srednje' },
  { word: 'klizalište', difficulty: 'srednje' },
  { word: 'rolšuhe', difficulty: 'srednje' },
  { word: 'skateboard', difficulty: 'srednje' },
  { word: 'skijanje', difficulty: 'srednje' },
  { word: 'bicikl', difficulty: 'srednje' },
  { word: 'motocikl', difficulty: 'srednje' },
  { word: 'helikopter', difficulty: 'srednje' },
  { word: 'podmornica', difficulty: 'srednje' },
  { word: 'akvarijum', difficulty: 'srednje' },
  { word: 'plaža', difficulty: 'srednje' },
  { word: 'planina', difficulty: 'srednje' },
  { word: 'šuma', difficulty: 'srednje' },
  { word: 'rijeka', difficulty: 'srednje' },
  { word: 'jezero', difficulty: 'srednje' },
  { word: 'parking', difficulty: 'srednje' },
  { word: 'restoran', difficulty: 'srednje' },
  { word: 'muzej', difficulty: 'srednje' },
  { word: 'stadion', difficulty: 'srednje' },
  { word: 'bolnica', difficulty: 'srednje' },
  { word: 'apoteka', difficulty: 'srednje' },
  { word: 'biblioteka', difficulty: 'srednje' },
  { word: 'teniski teren', difficulty: 'srednje' },
  { word: 'fudbalski gol', difficulty: 'srednje' },
  { word: 'košarkaška koš', difficulty: 'srednje' },
  { word: 'boks ring', difficulty: 'srednje' },
  { word: 'tramvaj', difficulty: 'srednje' },
  { word: 'traktor', difficulty: 'srednje' },
  { word: 'excavator', difficulty: 'srednje' },
  { word: 'vatrogasno vozilo', difficulty: 'srednje' },
  { word: 'policijski auto', difficulty: 'srednje' },
  { word: 'ambulanta', difficulty: 'srednje' },
  { word: 'semafor', difficulty: 'srednje' },
  { word: 'križ', difficulty: 'srednje' },
  { word: 'kompas', difficulty: 'srednje' },
  { word: 'teleskop', difficulty: 'srednje' },
  { word: 'mikroskop', difficulty: 'srednje' },
  { word: 'pingpong', difficulty: 'srednje' },
  { word: 'badminton', difficulty: 'srednje' },
  { word: 'bejzbol', difficulty: 'srednje' },
  { word: 'hokej', difficulty: 'srednje' },
  { word: 'tenis', difficulty: 'srednje' },
  { word: 'golf', difficulty: 'srednje' },
  { word: 'surfanje', difficulty: 'srednje' },
  { word: 'padobran', difficulty: 'srednje' },
  { word: 'bungee jumping', difficulty: 'srednje' },

  // TESKO
  { word: 'gravitacija', difficulty: 'tesko' },
  { word: 'demokratija', difficulty: 'tesko' },
  { word: 'evolucija', difficulty: 'tesko' },
  { word: 'revolucija', difficulty: 'tesko' },
  { word: 'inflacija', difficulty: 'tesko' },
  { word: 'pandemija', difficulty: 'tesko' },
  { word: 'nostalгija', difficulty: 'tesko' },
  { word: 'zavjera', difficulty: 'tesko' },
  { word: 'paradoks', difficulty: 'tesko' },
  { word: 'iluzija', difficulty: 'tesko' },
  { word: 'labirint', difficulty: 'tesko' },
  { word: 'karantena', difficulty: 'tesko' },
  { word: 'kamuflаža', difficulty: 'tesko' },
  { word: 'ekosistem', difficulty: 'tesko' },
  { word: 'reciklаža', difficulty: 'tesko' },
  { word: 'globalnog zagrijavanje', difficulty: 'tesko' },
  { word: 'crna rupa', difficulty: 'tesko' },
  { word: 'paralela', difficulty: 'tesko' },
  { word: 'mirovina', difficulty: 'tesko' },
  { word: 'karijera', difficulty: 'tesko' },
  { word: 'diplomacija', difficulty: 'tesko' },
  { word: 'šampionat', difficulty: 'tesko' },
  { word: 'olimpiada', difficulty: 'tesko' },
  { word: 'dokumentarаc', difficulty: 'tesko' },
  { word: 'improvizacija', difficulty: 'tesko' },
  { word: 'telepатija', difficulty: 'tesko' },
  { word: 'amnezija', difficulty: 'tesko' },
  { word: 'hiперpросtor', difficulty: 'tesko' },
  { word: 'virtualna realnost', difficulty: 'tesko' },
  { word: 'vještačka inteligencija', difficulty: 'tesko' },
  { word: 'blockchain', difficulty: 'tesko' },
  { word: 'kvantna fizika', difficulty: 'tesko' },
  { word: 'crni market', difficulty: 'tesko' },
  { word: 'haos teorija', difficulty: 'tesko' },
  { word: 'multivers', difficulty: 'tesko' },
  { word: 'naučna fantastika', difficulty: 'tesko' },
  { word: 'apokalipsa', difficulty: 'tesko' },
  { word: 'renesansa', difficulty: 'tesko' },
  { word: 'industrijska revolucija', difficulty: 'tesko' },
  { word: 'hologram', difficulty: 'tesko' },
  { word: 'teleportacija', difficulty: 'tesko' },
  { word: 'kloniranje', difficulty: 'tesko' },
  { word: 'biotehnologija', difficulty: 'tesko' },
  { word: 'nanotehnologija', difficulty: 'tesko' },
  { word: 'svjest', difficulty: 'tesko' },
  { word: 'deja vu', difficulty: 'tesko' },
  { word: 'fenomen', difficulty: 'tesko' },
  { word: 'katаstrofa', difficulty: 'tesko' },
  { word: 'preживljavanje', difficulty: 'tesko' },
  { word: 'utopija', difficulty: 'tesko' },
];

export function getRandomWords(count: number): string[] {
  const shuffled = [...DRAWING_WORDS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count).map((e) => e.word);
}

export function buildWordHint(word: string): string {
  return word
    .split(' ')
    .map((part) => part.split('').map(() => '_').join(' '))
    .join('   ');
}
